/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Error = { 'alreadyExists' : null } |
  { 'invalidInput' : string } |
  { 'notFound' : null } |
  { 'unauthorized' : null };
export interface Restaurant {
  'backgroundColor' : string,
  'backgroundImageUrl' : string,
  'city' : string,
  'name' : string,
  'createdAt' : bigint,
  'slug' : string,
  'description' : string,
  'isActive' : boolean,
  'restaurantId' : string,
  'logoUrl' : string,
  'pdfMenuUrl' : string,
}
export interface RestaurantInput {
  'backgroundColor' : [] | [string],
  'backgroundImageUrl' : [] | [string],
  'city' : string,
  'name' : string,
  'slug' : string,
  'description' : string,
  'isActive' : boolean,
  'logoUrl' : [] | [string],
  'pdfMenuUrl' : [] | [string],
}
export interface RestaurantPublic {
  'name' : string,
  'slug' : string,
  'description' : string,
  'isActive' : boolean,
  'restaurantId' : string,
  'logoUrl' : string,
}
export type Result = { 'ok' : Restaurant } |
  { 'err' : Error };
export type Result_1 = { 'ok' : User } |
  { 'err' : Error };
export type Result_2 = { 'ok' : null } |
  { 'err' : Error };
export interface UpdateRestaurantInput {
  'backgroundColor' : [] | [string],
  'backgroundImageUrl' : [] | [string],
  'city' : [] | [string],
  'name' : [] | [string],
  'slug' : [] | [string],
  'description' : [] | [string],
  'isActive' : [] | [boolean],
  'restaurantId' : string,
  'logoUrl' : [] | [string],
  'pdfMenuUrl' : [] | [string],
}
export interface User {
  'userId' : Principal,
  'createdAt' : bigint,
  'role' : UserRole,
}
export type UserRole = { 'WAITER' : null } |
  { 'MANAGER' : null } |
  { 'SUPER_ADMIN' : null } |
  { 'KITCHEN' : null };
export interface _SERVICE {
  'createRestaurant' : ActorMethod<[RestaurantInput], Result>,
  'getCurrentUserRole' : ActorMethod<[], [] | [UserRole]>,
  'getMyRestaurant' : ActorMethod<[], [] | [Restaurant]>,
  'getRestaurantBySlug' : ActorMethod<[string], [] | [RestaurantPublic]>,
  'getRestaurantPublic' : ActorMethod<[string], [] | [RestaurantPublic]>,
  'linkManagerToRestaurant' : ActorMethod<[string, string], Result_2>,
  'registerUser' : ActorMethod<[], Result_1>,
  'updateRestaurant' : ActorMethod<[string, UpdateRestaurantInput], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];