/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Restaurant = IDL.Record({
  'backgroundColor' : IDL.Text,
  'backgroundImageUrl' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'restaurantId' : IDL.Text,
  'logoUrl' : IDL.Text,
  'pdfMenuUrl' : IDL.Text,
});
export const Error = IDL.Variant({
  'alreadyExists' : IDL.Null,
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const Result_2 = IDL.Variant({ 'ok' : Restaurant, 'err' : Error });
export const UserRole = IDL.Variant({
  'WAITER' : IDL.Null,
  'MANAGER' : IDL.Null,
  'SUPER_ADMIN' : IDL.Null,
  'KITCHEN' : IDL.Null,
});
export const RestaurantPublic = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'restaurantId' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const User = IDL.Record({
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'role' : UserRole,
});
export const Result = IDL.Variant({ 'ok' : User, 'err' : Error });

export const idlService = IDL.Service({
  'addRestaurant' : IDL.Func([Restaurant], [Result_2], []),
  'getCurrentUserRole' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
  'getLinkedRestaurant' : IDL.Func([], [IDL.Opt(Restaurant)], ['query']),
  'getRestaurantPublic' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RestaurantPublic)],
      ['query'],
    ),
  'linkManagerToRestaurant' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [Result_1],
      [],
    ),
  'registerUser' : IDL.Func([UserRole], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Restaurant = IDL.Record({
    'backgroundColor' : IDL.Text,
    'backgroundImageUrl' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'restaurantId' : IDL.Text,
    'logoUrl' : IDL.Text,
    'pdfMenuUrl' : IDL.Text,
  });
  const Error = IDL.Variant({
    'alreadyExists' : IDL.Null,
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const Result_2 = IDL.Variant({ 'ok' : Restaurant, 'err' : Error });
  const UserRole = IDL.Variant({
    'WAITER' : IDL.Null,
    'MANAGER' : IDL.Null,
    'SUPER_ADMIN' : IDL.Null,
    'KITCHEN' : IDL.Null,
  });
  const RestaurantPublic = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'restaurantId' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const User = IDL.Record({
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'role' : UserRole,
  });
  const Result = IDL.Variant({ 'ok' : User, 'err' : Error });
  
  return IDL.Service({
    'addRestaurant' : IDL.Func([Restaurant], [Result_2], []),
    'getCurrentUserRole' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
    'getLinkedRestaurant' : IDL.Func([], [IDL.Opt(Restaurant)], ['query']),
    'getRestaurantPublic' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RestaurantPublic)],
        ['query'],
      ),
    'linkManagerToRestaurant' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [Result_1],
        [],
      ),
    'registerUser' : IDL.Func([UserRole], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };