/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RestaurantInput = IDL.Record({
  'backgroundColor' : IDL.Opt(IDL.Text),
  'backgroundImageUrl' : IDL.Opt(IDL.Text),
  'city' : IDL.Text,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'logoUrl' : IDL.Opt(IDL.Text),
  'pdfMenuUrl' : IDL.Opt(IDL.Text),
});
export const Restaurant = IDL.Record({
  'backgroundColor' : IDL.Text,
  'backgroundImageUrl' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'restaurantId' : IDL.Text,
  'logoUrl' : IDL.Text,
  'pdfMenuUrl' : IDL.Text,
});
export const Error = IDL.Variant({
  'alreadyExists' : IDL.Null,
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : Restaurant, 'err' : Error });
export const UserRole = IDL.Variant({
  'WAITER' : IDL.Null,
  'MANAGER' : IDL.Null,
  'SUPER_ADMIN' : IDL.Null,
  'KITCHEN' : IDL.Null,
});
export const RestaurantPublic = IDL.Record({
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'restaurantId' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const User = IDL.Record({
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'role' : UserRole,
});
export const Result_1 = IDL.Variant({ 'ok' : User, 'err' : Error });
export const UpdateRestaurantInput = IDL.Record({
  'backgroundColor' : IDL.Opt(IDL.Text),
  'backgroundImageUrl' : IDL.Opt(IDL.Text),
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'slug' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Opt(IDL.Bool),
  'restaurantId' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
  'pdfMenuUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'createRestaurant' : IDL.Func([RestaurantInput], [Result], []),
  'getCurrentUserRole' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
  'getMyRestaurant' : IDL.Func([], [IDL.Opt(Restaurant)], ['query']),
  'getRestaurantBySlug' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RestaurantPublic)],
      ['query'],
    ),
  'getRestaurantPublic' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RestaurantPublic)],
      ['query'],
    ),
  'linkManagerToRestaurant' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'registerUser' : IDL.Func([], [Result_1], []),
  'updateRestaurant' : IDL.Func(
      [IDL.Text, UpdateRestaurantInput],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RestaurantInput = IDL.Record({
    'backgroundColor' : IDL.Opt(IDL.Text),
    'backgroundImageUrl' : IDL.Opt(IDL.Text),
    'city' : IDL.Text,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'logoUrl' : IDL.Opt(IDL.Text),
    'pdfMenuUrl' : IDL.Opt(IDL.Text),
  });
  const Restaurant = IDL.Record({
    'backgroundColor' : IDL.Text,
    'backgroundImageUrl' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'restaurantId' : IDL.Text,
    'logoUrl' : IDL.Text,
    'pdfMenuUrl' : IDL.Text,
  });
  const Error = IDL.Variant({
    'alreadyExists' : IDL.Null,
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : Restaurant, 'err' : Error });
  const UserRole = IDL.Variant({
    'WAITER' : IDL.Null,
    'MANAGER' : IDL.Null,
    'SUPER_ADMIN' : IDL.Null,
    'KITCHEN' : IDL.Null,
  });
  const RestaurantPublic = IDL.Record({
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'restaurantId' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const User = IDL.Record({
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'role' : UserRole,
  });
  const Result_1 = IDL.Variant({ 'ok' : User, 'err' : Error });
  const UpdateRestaurantInput = IDL.Record({
    'backgroundColor' : IDL.Opt(IDL.Text),
    'backgroundImageUrl' : IDL.Opt(IDL.Text),
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'slug' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Opt(IDL.Bool),
    'restaurantId' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
    'pdfMenuUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'createRestaurant' : IDL.Func([RestaurantInput], [Result], []),
    'getCurrentUserRole' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
    'getMyRestaurant' : IDL.Func([], [IDL.Opt(Restaurant)], ['query']),
    'getRestaurantBySlug' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RestaurantPublic)],
        ['query'],
      ),
    'getRestaurantPublic' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RestaurantPublic)],
        ['query'],
      ),
    'linkManagerToRestaurant' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'registerUser' : IDL.Func([], [Result_1], []),
    'updateRestaurant' : IDL.Func(
        [IDL.Text, UpdateRestaurantInput],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };